
# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Holocene Climate Intro to Proxy Systems
author: Aidan Starr
logo: cam_logo.jpg

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/AidanStarr/psm_practical  # Online location of book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
